update 00-25-90-a7-79-1a

diff --git a/ipxe/mac/00-25-90-a7-79-1a b/ipxe/mac/00-25-90-a7-79-1a
--- a/ipxe/mac/00-25-90-a7-79-1a
+++ b/ipxe/mac/00-25-90-a7-79-1a
@@ -1,14 +1,12 @@
 #!ipxe
-#imgfree
-
-set script
-set append loglevel=3 user=docker console=ttyS0 console=tty nomodeset norestore base script=${script}
-set kernel http://pi:8080/boot/boot2docker/vmlinuz64
-set initrd http://pi:8080/boot/boot2docker/initrd.img
-
-
-
-imgfree
-kernel ${kernel} ${append}
-initrd ${initrd}
-boot
+dhcp
+echo Starting Ubuntu x64 installer for ${hostname}
+set base-url http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64
+kernel ${base-url}/linux
+initrd ${base-url}/initrd.gz
+imgargs linux auto=true url=http://pi:8080/p/pxe/ks/ubuntu-utopic.ipxe.ks
+boot || 
+# If everything failed, give the user some options
+echo Boot from ${base-url} failed
+prompt --key 0x197e --timeout 2000 Press F12 to investigate || exit
+shell
